CREATE TRIGGER supprimerSite ON SITE
INSTEAD OF DELETE AS
BEGIN
	DECLARE @idSite int

	DECLARE CursorSite CURSOR FOR SELECT idSite FROM DELETED
	OPEN CursorSite
	FETCH CursorSite INTO @idSite
	WHILE @@FETCH_STATUS=0
	BEGIN
		DELETE FROM MATERIEL WHERE idSite=@idSite
		DELETE FROM SITE WHERE idSite=@idSite
		FETCH CursorSite INTO @idSite
	END
	CLOSE CursorSite
	DEALLOCATE CursorSite
END